djangotp1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
      path('', include('section1.urls')),
    path('admin/', admin.site.urls),
]

gestcom/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
      path('', include('gestionnaire.urls')),  # Inclure les URLs de l'application gestionnaire
       path('categorie/', include('categorie.urls')),  
          path('quartier/', include('quartier.urls')),  
             path('maison/', include('maison.urls')),  
]

gestionnaire/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = "gestionnaire"
urlpatterns = [
 
    path('', views.login_view, name='login'),
    
  path('dashboard/<int:matricule>/', views.dashboard, name='dashboard'),
  ]

maison/urls.py
from . import views
from django.urls import path,include

app_name = "maison"
urlpatterns = [

      path('<int:matricule>/', views.home, name='home'),
      path('form/<int:matricule>/', views.formulaire, name='formulaire'),
      path('forme/<int:id>/', views.updateform, name='form'),
      path('ajouter/<int:matricule>/', views.add, name='add'),
      path('delete/<int:id>/', views.delete, name='delete'),
      path('update/<int:id>/', views.update, name='update'),
      path('forme/<int:id>/', views.updateform, name='form'),
      path('detail/<int:id>/', views.detail, name='detail'),

    



]

maison/models.py
from django.db import models
from quartier.models import Quartier
from categorie.models import Categorie

from gestionnaire.models import Gestionnaire

# Create your models here.
class Maison(models.Model):
    id = models.BigAutoField(primary_key=True)  # <== CORRECT ICI
    adresse = models.CharField(max_length=100, default="blue",unique=True)
    surperficie =models.FloatField()
    quartier =  models.ForeignKey(Quartier,on_delete=models.CASCADE)
    categorie = models.ForeignKey(Categorie,on_delete=models.CASCADE)
    gestionnaire =  models.ForeignKey(Gestionnaire,on_delete=models.CASCADE)

maison/views.py
from django.shortcuts import render,redirect
from gestionnaire.models import Gestionnaire
from .models import Maison
from quartier.models import Quartier
from categorie.models import Categorie
from django.urls import reverse

from django.http import HttpResponse

from gestionnaire.models import Gestionnaire

# Create your views here.
def home(request,matricule):
      gestionnaires = Gestionnaire.objects.get( pk=matricule)
     
  
      categories  = Maison.objects.filter(gestionnaire=gestionnaires)
      contexte ={ 'categories': categories ,'matricule':matricule}
      return render( request ,'maison/home.html',contexte )
def formulaire(request,matricule):
      add ="ajouter"
      gestionnaires = Gestionnaire.objects.get( pk=matricule)
      Listecategories= Categorie.objects.filter(gestionnaire=gestionnaires)
      Listequartiers= Quartier.objects.filter(gestionnaire=gestionnaires)
      action="Ajouter"
      contexte ={ 'matricule':matricule ,'add':add,'Listecategories':Listecategories,'Listequartiers': Listequartiers,'action':action } 
      return render( request ,'maison/form.html',contexte )




def add(request,matricule):
        add ="ajouter"
        action="Ajouter"
        adresse = request.POST.get('adresse')
        quartier_id = request.POST.get('quartier')
        categorie_id = request.POST.get('categorie')
        surface = float(request.POST.get('superficie'))
        if surface <0:
            surface = -1*surface
        categories= Categorie.objects.get(pk=categorie_id)
        insuffisance =False
        notUnique = False
        quartiers= Quartier.objects.get(pk=quartier_id)
        if surface>quartiers.reste_surface():
             insuffisance =True
        
        
        quartiers= Quartier.objects.get(pk=quartier_id)
        if Maison.objects.filter(adresse=adresse).exists():
              notUnique = True
            
        if insuffisance == True or notUnique == True:
              gestionnaires = Gestionnaire.objects.get( pk=matricule)
              Listecategories= Categorie.objects.filter(gestionnaire=gestionnaires)
              Listequartiers= Quartier.objects.filter(gestionnaire=gestionnaires)
              contexte ={ 'insuffisance':insuffisance,'notUnique':notUnique,'add':add,'action':action,'Listecategories':Listecategories,'Listequartiers': Listequartiers,'matricule': matricule}
              return  render( request ,'maison/form.html',contexte )
        else:
                gestionnaires = Gestionnaire.objects.get( pk=matricule)
                maison = Maison( adresse=adresse,surperficie=surface,  categorie=categories , quartier=quartiers, gestionnaire=gestionnaires)
                maison.save()
                url = reverse('maison:home', args=[matricule])
        return   redirect(url)
      

   
   
   
   
def delete(request,id):
       maison =Maison.objects.get( pk=id)
       quartiers= Quartier.objects.get(pk=maison.quartier_id)
       matricule= quartiers.gestionnaire.matricule
       url = reverse('maison:home', args=[matricule])
       maison.delete()
       return   redirect(url)  
        
        
def updateform (request ,id) :
      add ="update"
      action="Modifier"
      categorie =Maison.objects.get( pk=id)
      matricule= categorie.gestionnaire.matricule
      gestionnaires = Gestionnaire.objects.get( pk=matricule)
      Listecategories= Categorie.objects.filter(gestionnaire=gestionnaires)
      Listequartiers = Quartier.objects.filter()
      contexte ={ 'matricule':id ,'add':add , 'maison': categorie  ,'action':action,'Listecategories':Listecategories,'Listequartiers':Listequartiers}
      return render( request ,'maison/form.html',contexte )
   
      
def update(request,id):
      adresse = request.POST.get('adresse')
      quartier_id = request.POST.get('quartier')
      categorie_id = request.POST.get('categorie')
      surface = float(request.POST.get('superficie'))
      if surface <0:
            surface = -1*surface
      categorie= Categorie.objects.get(pk=categorie_id)
      maison = Maison.objects.get(pk=id)
      matricule= categorie.gestionnaire.matricule
      url = reverse('maison:home', args=[matricule])
      maison.adresse=adresse 
      maison.surperficie=surface 
      maison.categorie =Categorie.objects.get(pk=categorie_id)
      maison.quartier=Quartier.objects.get(pk=quartier_id)
      maison.save()
      return redirect(url)  

def detail (request,id):
     maison = Maison.objects.get(pk=id) 
     contexte ={ 'maison':maison}             
     return render( request ,'maison/detail.html',contexte )  
        
        
        
        
        
        
        
#
# quartier.save(),'Listequartiers':Listequartiers

templates/maison/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Détails de la Maison</title>
    <link rel="stylesheet" href="{% static 'maison/css/detail.css' %}">
</head>
<body>
    <header>Détails de la Maison</header>

    <div class="container">
        <div class="detail-item"><strong>Adresse :</strong> {{ maison.adresse }}</div>
        <div class="detail-item"><strong>Superficie :</strong> {{ maison.surperficie }} m²</div>
        <div class="detail-item"><strong>Quartier :</strong> {{ maison.quartier.nom }}</div>
        <div class="detail-item"><strong>Catégorie :</strong> {{ maison.categorie.nom }}</div>
        <div class="detail-item"><strong>Gestionnaire :</strong> {{ maison.gestionnaire.nom }}</div>


        <a  style="text-decoration:none; text-align:center;" href="{% url "maison:home" maison.gestionnaire.matricule %}" class="add-btn" >Retourner<a/>

    </div>

</body>
</html>

templates/maison/form.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Maison</title>
    <link rel="stylesheet" href="{% static 'maison/css/form.css' %}">
</head>
<body>

<div class="form-container">
    {% if add == "ajouter" %}
        <h2>Ajouter une maison</h2>
    {% else %}
        <h2>Modifier une maison</h2>
    {% endif %}
   
    <form action="/maison/{{ add }}/{{ matricule }}/" method="post">
        {% csrf_token %}

       

        {% if add == "ajouter" %}
           <label for="adresse">Adresse :</label>
           <input type="text" id="adresse" name="adresse" value="{{ adresse }}" required>    
             {% if  notUnique == True %}
            <p class="error-message">cet addrese est deja attribue a une masion</p>
             {% endif %}
            <label for="quartier">Choisissez un quartier :</label>
            <select id="quartier" name="quartier" required>
             {% for quartier in Listequartiers %}
             <option value="{{quartier.id}}">{{quartier.nom}}</option>
              
                {% endfor %}
            </select>
               {% if  insuffisance == True %}
            <p class="error-message">ce quartier est deja pleinr</p>
               {% endif %}
            <label for="categorie">Type de maison :</label>
            <select id="categorie" name="categorie" required>
             {% for categorie in  Listecategories %}
                <option value="{{categorie.id}}">{{categorie.nom}}</option>
             {% endfor %}
            </select>
             {% if  not  Listecategories %}
            <p class="error-message">vous ajouter de masion sans creer les categories </p>

            {% endif %}
            <label for="superficie">Superficie (en m²) :</label>
            <input type="number" id="superficie" name="superficie"
                   {% if add != "Ajouter" %} value="{{ superficie }}"{% endif %}
                   required step="0.01">
                <div class="form-buttons">
                <input type="submit" value="{{ action }}">
                <input type="reset" value="Annuler">
            </div>
        {% else %}
             <label for="adresse">Adresse :</label>
             <input type="text" id="adresse" name="adresse" value="{{ maison.adresse }}" required>    
             <label for="quartier">Choisissez un quartier :</label>
             <select id="quartier" name="quartier" required>
                <option value="{{maison.quartier.id}}" selected>{{maison.quartier.nom}}</option>
              {% for quartier in Listequartiers %}
              {% if quartier.id != maison.quartier.id %}
              <option value="{{quartier.id}}">{{quartier.nom}}</option>
              {% endif %}
               
                 {% endfor %}
             </select>
            <label for="categorie">Type de maison :</label>
            <select id="categorie" name="categorie" required>
                <option value="{{maison.categorie.id}}" selected>{{maison.categorie.nom}}</option>
             {% for categorie in  Listecategories %}
             {% if categorie.id != maison.categorie.id %}
             <option value="{{categorie.id}}">{{categorie.nom}}</option>
             {% endif %}
             {% endfor %}
            </select>
            <label for="superficie">Superficie (en m²) :</label>
            <input type="number" id="superficie" name="superficie"
                   {% if add != "Ajouter" %} value={{maison.surperficie}} {% endif %}
                   required step="0.01">
            <div class="form-buttons">
                <input type="submit" value="{{ action }}">
                <input type="reset" value="Annuler">
            </div>
        {% endif %}

       

      
    </form>
    <!-- <option value="{{categorie.id}}">{{categorie.nom}}</option>> <option value="{{maison.quarter.id}}" selected>{{maison.quartier.nom}}</option>-->

    <div class="retour">
        <a href="{% url "maison:home" matricule %}">Retourner</a>
    </div>
</div>

</body>
</html>

templates/maison/home.html
 {% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Maisons</title>
   
        <link rel="stylesheet" href="{% static 'categorie/css/home.css' %}">
    
</head>
<body>
<header>Maisons</header>

<div class="container">
    <a  style="text-decoration:none; text-align:center;" href="{% url 'maison:formulaire' matricule     %}" class="add-btn" >+ Ajouter une catégorie</a>
    <a  style="text-decoration:none; text-align:center;" href="{% url 'gestionnaire:dashboard' matricule     %}" class="add-btn" >Retourner</a>

    <ul class="category-list">
      {% for categorie in  categories %}
       <li class="category-item">
            <span>{{categorie.adresse}}</span>
            <div class="action-buttons">
                <a href="{% url 'maison:form' categorie.id  %}" title="Modifier cette catégorie">
                <img   style="width:20px; height:20px;" src="{% static 'categorie/img/modifier.svg' %}" alt="supprimer">
                </a>
                <a href="{% url 'maison:delete' categorie.id  %}" title="Supprimer cette catégorie">
                <img   style="width:20px; height:20px;" src="{% static 'categorie/img/supprimer.svg' %}" alt="supprimer">
                </a>
                <a href="{% url 'maison:detail' categorie.id  %}" title="Voir les détails de cette catégorie">
                <img   style="width:20px; height:20px;" src="{% static 'categorie/img/detail.svg' %}" alt="supprimer">
                </a>
            </div>
        </li>
        {% endfor %}
        
    </ul>
</div>

</body>
</html>