categorie/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "categorie"
urlpatterns = [

    path('<int:matricule>/', views.home, name='home'),
      path('form/<int:matricule>/', views.formulaire, name='formulaire'),
          path('forme/<int:id>/', views.updateform, name='form'),
       path('ajouter/<int:matricule>/', views.add, name='add'),
      path('delete/<int:id>/', views.delete, name='delete'),
       path('update/<int:id>/', views.update, name='update'),





]

djangotp1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
      path('', include('section1.urls')),
    path('admin/', admin.site.urls),
]

gestcom/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
      path('', include('gestionnaire.urls')),  # Inclure les URLs de l'application gestionnaire
       path('categorie/', include('categorie.urls')),  
          path('quartier/', include('quartier.urls')),  
             path('maison/', include('maison.urls')),  
]

gestionnaire/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = "gestionnaire"
urlpatterns = [
 
    path('', views.login_view, name='login'),
    
  path('dashboard/<int:matricule>/', views.dashboard, name='dashboard'),
  ]

maison/urls.py
from . import views
from django.urls import path,include

app_name = "maison"
urlpatterns = [

      path('<int:matricule>/', views.home, name='home'),
      path('form/<int:matricule>/', views.formulaire, name='formulaire'),
      path('forme/<int:id>/', views.updateform, name='form'),
      path('ajouter/<int:matricule>/', views.add, name='add'),
      path('delete/<int:id>/', views.delete, name='delete'),
      path('update/<int:id>/', views.update, name='update'),
      path('forme/<int:id>/', views.updateform, name='form'),
      path('detail/<int:id>/', views.detail, name='detail'),

    



]

categorie/models.py
from django.db import models
from gestionnaire.models import Gestionnaire


# Create your models here.
class Categorie(models.Model):
      id = models.BigAutoField(primary_key=True)  # <== CORRECT ICI
      nom = models.CharField(max_length=100, default="blue")
      gestionnaire = models.ForeignKey( Gestionnaire,on_delete=models.CASCADE)

categorie/views.py
from django.shortcuts import render,redirect
from gestionnaire.models import Gestionnaire
from .models import Categorie
from django.http import HttpResponse
from django.urls import reverse
# Create your views here.
def home(request,matricule):
      gestionnaires = Gestionnaire.objects.get( pk=matricule)
      categories = Categorie.objects.filter(gestionnaire=gestionnaires)
      contexte ={ 'categories': categories ,'matricule':matricule}
      return render( request ,'categorie/home.html',contexte )
def formulaire(request,matricule):
      add ="ajouter"
      action="Ajouter"
      contexte ={ 'matricule':matricule ,'add':add  ,'action':action}
      return render( request ,'categorie/form.html',contexte )



def add(request,matricule):
       name = request.POST.get('nom_categorie')
       gestionnaires = Gestionnaire.objects.get( pk=matricule)
       categorie = Categorie( nom=name,gestionnaire=gestionnaires)
       url = reverse('categorie:home', args=[matricule])
       categorie.save()
       return redirect(url)
def delete(request,id):
       categorie =Categorie.objects.get( pk=id)
       matricule= categorie.gestionnaire.matricule
       url = reverse('categorie:home', args=[matricule])
       categorie.delete()
       return redirect(url)
def updateform (request ,id) :
      add ="update"
      action="Modifier"
      categorie =Categorie.objects.get( pk=id)
      contexte ={ 'matricule':id ,'add':add , 'nom': categorie.nom  ,'action':action}
      return render( request ,'categorie/form.html',contexte )
   
       
def update(request,id):
       name = request.POST.get('nom_categorie')
       categorie = Categorie.objects.get(pk=id)
       matricule= categorie.gestionnaire.matricule
       url = reverse('categorie:home', args=[matricule])
       categorie.nom=name
       categorie.save()
       return redirect(url)        
      
      

templates/categorie/form.html
 {% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title> Catégorie</title>
     <link rel="stylesheet" href="{% static 'categorie/css/form.css' %}">
    
</head>
<body>

<div class="form-container">
  {% if add == "ajouter" %}
  
   <h2>Ajouter une Catégorie</h2>
  {% else %}
  <h2>Modifier une Catégorie</h2>
{% endif %}
   
    <form action="/categorie/{{add}}/{{matricule}}/" method="post">
     {% csrf_token %}
        <label for="nom_categorie">Nom de la catégorie :</label>
         {% if add == "ajouter" %}
  
   <input type="text" id="nom_categorie" name="nom_categorie" required>
  {% else %}
  <input type="text" id="nom_categorie" name="nom_categorie" value="{{nom}}" required>
{% endif %}
        

        <div class="form-buttons">
            <input type="submit" value="{{action}}">
            <input type="reset" value="Annuler">
        </div>
    </form>

    <div class="retour">
        <a href="{% url "categorie:home" matricule %}">Retourner</a>
    </div>
</div>

</body>
</html>

templates/categorie/home.html
 {% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Catégories</title>
   
        <link rel="stylesheet" href="{% static 'categorie/css/home.css' %}">
    
</head>
<body>
<header>Catégories</header>

<div class="container">
    <a  style="text-decoration:none; text-align:center;" href="{% url 'categorie:formulaire' matricule     %}" class="add-btn" >+ Ajouter une catégorie</a>
    <a  style="text-decoration:none; text-align:center;" href="{% url 'gestionnaire:dashboard' matricule     %}" class="add-btn" >Retourner</a>
    <ul class="category-list">
      {% for categorie in  categories %}
       <li class="category-item">
            <span>{{categorie.nom}}</span>
            <div class="action-buttons">
                <a href="{% url 'categorie:form' categorie.id  %}" title="Modifier cette catégorie">
                <img   style="width:20px; height:20px;" src="{% static 'categorie/img/modifier.svg' %}" alt="supprimer">
                </a>
                <a href="{% url 'categorie:delete' categorie.id  %}" title="Supprimer cette catégorie">
                <img   style="width:20px; height:20px;" src="{% static 'categorie/img/supprimer.svg' %}" alt="supprimer">
                </a>
                <a href="#" title="Voir les détails de cette catégorie">
                <img   style="width:20px; height:20px;" src="{% static 'categorie/img/detail.svg' %}" alt="supprimer">
                </a>
            </div>
        </li>
        {% endfor %}
        
    </ul>
</div>

</body>
</html>